import Head from "next/head";

// components
import HomeContents from "@/contents/Home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fusion-APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContents />
    </>
  );
}
